MSHRCS.Presentation/Models/AcademicDisciplineViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MSHRCS.Presentation.Models
{
	public class AcademicDisciplineViewModel
	{
		public int Id { get; set; }

		[Required(AllowEmptyStrings = false, ErrorMessage = "Необходимо ввести код!")]
		[DisplayName("Код")]
		public string Code { get; set; }

		[DisplayName("Название")]
		[Required(AllowEmptyStrings = false, ErrorMessage = "Необходимо ввести название!")]
		public string Description { get; set; }
	}
}

MSHRCS.Presentation/Controllers/AcademicDisciplinesController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using MSHRCS.BusinessLogic.DataModel;
using MSHRCS.BusinessLogic.Enums;
using MSHRCS.BusinessLogic.Services.Interfaces;
using MSHRCS.BusinessLogic.UnitOfWork;
using MSHRCS.Presentation.Attributes;
using MSHRCS.Presentation.Models;

namespace MSHRCS.Presentation.Controllers
{
	[CustomAuthorize(RequiredUsers = new[] { UsersEnum.Administrator })]
	public class AcademicDisciplinesController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IAcademicDisciplineService _academicDisciplineService;

		public AcademicDisciplinesController(IUnitOfWork unitOfWork, IAcademicDisciplineService academicDisciplineService)
		{
			_unitOfWork = unitOfWork;
			_academicDisciplineService = academicDisciplineService;
		}

		public ViewResult Index()
		{
			var aDVM =
				Mapper.Map<IEnumerable<AcademicDiscipline>, IEnumerable<AcademicDisciplineViewModel>>(
					_academicDisciplineService.GetAll());
			return View(aDVM);
		}

		public ViewResult Details(int id)
		{
			var academicdiscipline = _academicDisciplineService.GetAll().First(ad => ad.Id == id);
			var aDVM = Mapper.Map<AcademicDiscipline, AcademicDisciplineViewModel>(academicdiscipline);
			return View(aDVM);
		}

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(AcademicDisciplineViewModel academicDisciplineViewModel)
		{
			if (!ModelState.IsValid)
			{
				return View(academicDisciplineViewModel);
			}

			var academicDiscipline = Mapper.Map<AcademicDisciplineViewModel, AcademicDiscipline>(academicDisciplineViewModel);
			_academicDisciplineService.AddOrUpdate(academicDiscipline);
			_unitOfWork.Commit();
			return RedirectToAction("Index");
		}

		public ActionResult Edit(int id)
		{
			var academicdiscipline = _academicDisciplineService.GetAll().First(ad => ad.Id == id);
			var aDVM = Mapper.Map<AcademicDiscipline, AcademicDisciplineViewModel>(academicdiscipline);
			return View(aDVM);
		}

		[HttpPost]
		public ActionResult Edit(AcademicDisciplineViewModel academicDisciplineViewModel)
		{
			if (!ModelState.IsValid)
			{
				return View(academicDisciplineViewModel);
			}

			var academicDiscipline = Mapper.Map<AcademicDisciplineViewModel, AcademicDiscipline>(academicDisciplineViewModel);

			_unitOfWork.Context.Entry(academicDiscipline).State = EntityState.Modified;
			_unitOfWork.Commit();
			return RedirectToAction("Index");
		}

		public ActionResult Delete(int id)
		{
			var academicdiscipline = _academicDisciplineService.GetAll().First(ad => ad.Id == id);
			var aDVM = Mapper.Map<AcademicDiscipline, AcademicDisciplineViewModel>(academicdiscipline);
			return View(aDVM);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			var academicdiscipline = _academicDisciplineService.GetAll().First(ad => ad.Id == id);
			_academicDisciplineService.Delete(academicdiscipline);
			_unitOfWork.Commit();
			return RedirectToAction("Index");
		}
	}
}

MSHRCS.Presentation/Views/AcademicDisciplines/Create.cshtml
@model MSHRCS.Presentation.Models.AcademicDisciplineViewModel
@{
	ViewBag.Title = "Создание предмета";
}
<div class="col-md-6 col-md-offset-3">
	@using (Html.BeginForm())
 {
		@Html.ValidationSummary(true)

		<fieldset>
			<legend>Новый предмет</legend>
			<table class="new-object-table">
				<tbody>
					<tr>
						<td class="field-name">@Html.LabelFor(model => model.Code)</td>
						<td class="field-value">@Html.TextBoxFor(model => model.Code, new { @class = "form-control" })</td>
						<td class="field-validation-error">@Html.ValidationMessageFor(model => model.Code)</td>
					</tr>
					<tr>
						<td class="field-name">@Html.LabelFor(model => model.Description)</td>
						<td class="field-value">@Html.TextBoxFor(model => model.Description, new { @class = "form-control" })</td>
						<td class="field-validation-error">@Html.ValidationMessageFor(model => model.Description)</td>
					</tr>
				</tbody>
			</table>

			<div class="margin-top">
				@Html.ActionLink("Вернуться к списку", "Index", "AcademicDisciplines", new { @class = "btn btn-default" })
				<input type="submit" value="Создать" class="btn btn-primary pull-right" />
			</div>
		</fieldset>
 }
</div>

MSHRCS.Presentation/Views/AcademicDisciplines/Delete.cshtml
@model MSHRCS.Presentation.Models.AcademicDisciplineViewModel
@{
    ViewBag.Title = "Удаление предмета";
}

<div class="col-md-6 col-md-offset-3">
    <h3>Вы уверены, что хотите удалить этот предмет?</h3>
    <fieldset>
        <legend>Предмет</legend>

        <table class="new-object-table table table-bordered">
            <tbody>
                <tr>
                    <td class="field-name">@Html.LabelFor(model => model.Code)</td>
                    <td class="">@Html.DisplayFor(model => model.Code)</td>
                </tr>
                <tr>
                    <td class="field-name">@Html.LabelFor(model => model.Description)</td>
                    <td class="">@Html.DisplayFor(model => model.Description)</td>
                </tr>
            </tbody>
        </table>

@*        <div class="form-inline">*@
@*            @Html.LabelFor(model => model.Code)*@
@*            @Html.DisplayFor(model => model.Code)*@
@*        </div>*@
@**@
@*        <div class="form-inline">*@
@*            @Html.LabelFor(model => model.Description)*@
@*            @Html.DisplayFor(model => model.Description)*@
@*        </div>*@
    </fieldset>
    @using (Html.BeginForm())
    {
        <p>
            @Html.ActionLink("Вернуться к списку", "Index", "AcademicDisciplines", new { @class = "btn btn-default" })
            <input type="submit" value="Удалить" class="btn btn-danger pull-right" />
        </p>
    }
</div>

MSHRCS.Presentation/Views/AcademicDisciplines/Details.cshtml
@model MSHRCS.Presentation.Models.AcademicDisciplineViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>AcademicDiscipline</legend>

    <div class="display-label">Code</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Code)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MSHRCS.Presentation/Views/AcademicDisciplines/Edit.cshtml
@model MSHRCS.Presentation.Models.AcademicDisciplineViewModel
@{
    ViewBag.Title = "Редактирование";
}
<div class="col-md-6 col-md-offset-3">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Предмет</legend>

            @Html.HiddenFor(model => model.Id)

            <table class="new-object-table">
                <tbody>
                    <tr>
                        <td class="field-name">@Html.LabelFor(model => model.Code)</td>
                        <td class="field-value">@Html.TextBoxFor(model => model.Code, new { @class = "form-control" })</td>
                        <td class="field-validation-error">@Html.ValidationMessageFor(model => model.Code)</td>
                    </tr>
                    <tr>
                        <td class="field-name">@Html.LabelFor(model => model.Description)</td>
                        <td class="field-value">@Html.TextBoxFor(model => model.Description, new { @class = "form-control" })</td>
                        <td class="field-validation-error">@Html.ValidationMessageFor(model => model.Description)</td>
                    </tr>
                </tbody>
            </table>

            <div class="margin-top">
                @Html.ActionLink("Вернуться к списку", "Index", "AcademicDisciplines", new { @class = "btn btn-default" })
                <input type="submit" value="Сохранить" class="btn btn-primary pull-right" />
            </div>
        </fieldset>
    }
</div>


MSHRCS.Presentation/Views/AcademicDisciplines/Index.cshtml
@using MSHRCS.BusinessLogic
@model IEnumerable<MSHRCS.Presentation.Models.AcademicDisciplineViewModel>
@{
	ViewBag.Title = "Предметы";
}

<div class="col-md-10 col-md-offset-1">
	@Html.ActionLink("Создать", "Create", "AcademicDisciplines", new { @class = "btn btn-default margin-bottom" })

	<table class="table table-bordered table-striped">
		<tr>
			<th class="text-center">Код
			</th>
			<th class="text-center">Название
			</th>
			<th class="text-center">Доступные действия</th>
		</tr>

		@foreach (var item in Model)
  {
			<tr>
				<td class="text-center">
					@Html.DisplayFor(modelItem => item.Code)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Description)
				</td>
				<td class="text-center">
					@Html.ActionLink(Constants.Edit, "Edit", new { id = item.Id }) | @Html.ActionLink(Constants.Delete, "Delete", new { id = item.Id })
				</td>
			</tr>
  }
	</table>
</div>