MSHRCS.Presentation/Controllers/GDCabinetController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using MSHRCS.BusinessLogic.DataModel;
using MSHRCS.BusinessLogic.Repository;
using MSHRCS.BusinessLogic.Services.Interfaces;
using MSHRCS.Presentation.Models;
using Newtonsoft.Json;

namespace MSHRCS.Presentation.Controllers
{
	public class GDCabinetController : Controller
	{
		private readonly IGDCabinetService _cabinetService;
		private readonly IGroupDisciplineService _groupDisciplineService;
		private MSHRCSchedulerContext db = new MSHRCSchedulerContext();

		public GDCabinetController(IGDCabinetService cabinetService, IGroupDisciplineService groupDisciplineService)
		{
			_cabinetService = cabinetService;
			_groupDisciplineService = groupDisciplineService;
		}

		public ViewResult Index()
		{
			var cabinets = _cabinetService.GetAllGDCabinets().ToList();

			var cabinetViewModels = Mapper.Map<IEnumerable<GDCabinet>, List<GDCabinetViewModel>>(cabinets);
			return View(cabinetViewModels);
		}

		public ViewResult Details(int id)
		{
			GDCabinet gdcabinet = db.GDCabinets.Find(id);
			return View(gdcabinet);
		}

		public ActionResult Create()
		{
			ViewBag.Lessons = new SelectList(db.Lessons, "Id", "Name");
			ViewBag.LessonTypes = new SelectList(db.LessonTypes, "Id", "Name");
			return View();
		}

		[HttpPost]
		public ActionResult Create(NewGDCabinetViewModel gdcabinet)
		{
			if (ModelState.IsValid)
			{
				return RedirectToAction("Index");
			}

			ViewBag.Lessons = new SelectList(db.Lessons, "Id", "Name");
			ViewBag.LessonTypes = new SelectList(db.LessonTypes, "Id", "Name");
			return View(gdcabinet);
		}
		public ActionResult Edit(int id)
		{
			GDCabinet gdcabinet = db.GDCabinets.Find(id);
			ViewBag.CabinetId = new SelectList(db.Cabinets, "Id", "Id", gdcabinet.CabinetId);
			ViewBag.GDId = new SelectList(db.GroupDisciplines, "Id", "Id", gdcabinet.GDId);
			ViewBag.LessonId = new SelectList(db.Lessons, "Id", "Name", gdcabinet.LessonId);
			ViewBag.LessonTypeId = new SelectList(db.LessonTypes, "Id", "Name", gdcabinet.LessonTypeId);
			ViewBag.SubstituteDGId = new SelectList(db.GroupDisciplines, "Id", "Id", gdcabinet.SubstituteDGId);
			return View(gdcabinet);
		}

		[HttpPost]
		public ActionResult Edit(GDCabinet gdcabinet)
		{
			if (ModelState.IsValid)
			{
				db.Entry(gdcabinet).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			ViewBag.CabinetId = new SelectList(db.Cabinets, "Id", "Id", gdcabinet.CabinetId);
			ViewBag.GDId = new SelectList(db.GroupDisciplines, "Id", "Id", gdcabinet.GDId);
			ViewBag.LessonId = new SelectList(db.Lessons, "Id", "Name", gdcabinet.LessonId);
			ViewBag.LessonTypeId = new SelectList(db.LessonTypes, "Id", "Name", gdcabinet.LessonTypeId);
			ViewBag.SubstituteDGId = new SelectList(db.GroupDisciplines, "Id", "Id", gdcabinet.SubstituteDGId);
			return View(gdcabinet);
		}

		public ActionResult Delete(int id)
		{
			GDCabinet gdcabinet = db.GDCabinets.Find(id);
			return View(gdcabinet);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			GDCabinet gdcabinet = db.GDCabinets.Find(id);
			db.GDCabinets.Remove(gdcabinet);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			db.Dispose();
			base.Dispose(disposing);
		}

		public JsonResult GetGroupDisciplineViewModels()
		{
			var groupDisciplines = _groupDisciplineService.GetAllGroupDisciplines();
			var groupDisciplineViewModels = Mapper.Map<IEnumerable<GroupDiscipline>, IEnumerable<GroupDisciplineViewModel>>(groupDisciplines);

			return Json(new { groupDisciplineViewModels }, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetCabinetLessonViewModels()
		{
			var cabinetLessons = _cabinetService.GetCabinetLessons(new DateTime(2015, 4, 6));
			var lessonAvailableCabinetsViewModels = Mapper.Map<Dictionary<Lesson, List<Cabinet>>, List<LessonAvailableCabinetsViewModel>>(cabinetLessons);

			return Json(new { lessonAvailableCabinetsViewModels }, JsonRequestBehavior.AllowGet);
		}
	}
}

MSHRCS.Presentation/Controllers/GroupDisciplineController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using MSHRCS.BusinessLogic.DataModel;
using MSHRCS.BusinessLogic.Services.Interfaces;
using MSHRCS.BusinessLogic.UnitOfWork;
using MSHRCS.Presentation.Models;
using Newtonsoft.Json;

namespace MSHRCS.Presentation.Controllers
{
	public class GroupDisciplineController : Controller
	{
		private readonly IGroupService _groupService;
		private readonly IAcademicDisciplineService _academicDisciplineService;
		private readonly ILessonService _lessonService;
		private readonly ITeacherService _teacherService;
		private readonly IGroupDisciplineService _groupDisciplineService;
		private readonly IUnitOfWork _unitOfWork;

		public GroupDisciplineController(IGroupService groupService, IAcademicDisciplineService academicDisciplineService,
			ILessonService lessonService, ITeacherService teacherService, IGroupDisciplineService groupDisciplineService,
			IUnitOfWork unitOfWork)
		{
			_groupService = groupService;
			_academicDisciplineService = academicDisciplineService;
			_lessonService = lessonService;
			_teacherService = teacherService;
			_groupDisciplineService = groupDisciplineService;
			_unitOfWork = unitOfWork;
		}

		public ViewResult Index()
		{
			var groupdisciplines = _groupDisciplineService.GetAllGroupDisciplines().ToList();
			var groupDisciplineViewModels = Mapper.Map<List<GroupDiscipline>, IEnumerable<GroupDisciplineViewModel>>(groupdisciplines);
			return View(groupDisciplineViewModels);
		}

		public ViewResult Details(int id)
		{
			var groupdiscipline = _groupDisciplineService.GetAllGroupDisciplines().First(gd => gd.Id == id);
			var groupDisciplineViewModel = Mapper.Map<GroupDiscipline, GroupDisciplineViewModel>(groupdiscipline);
			return View(groupDisciplineViewModel);
		}

		public ActionResult Create()
		{
			ViewBag.DisciplineId = new SelectList(_academicDisciplineService.GetAll(), "Id", "Code");
			ViewBag.GroupId = new SelectList(_groupService.GetAllGroups(), "Id", "Code");
			ViewBag.LessonTypes =
				_lessonService.GetLessonTypes()
					.Select(type => new SelectListItem { Selected = false, Text = type.Name, Value = type.Id.ToString() }).ToList();
			return View();
		}

		public ActionResult Edit(int id)
		{
			var groupdiscipline = _groupDisciplineService.GetAllGroupDisciplines().First(gd => gd.Id == id);
			var groupDisciplineViewModel = Mapper.Map<GroupDiscipline, GroupDisciplineViewModel>(groupdiscipline);
			return View(groupDisciplineViewModel);
		}

		[HttpPost]
		public ActionResult Edit(int gdId, string exitsedIds, string gdTeachers)
		{
			var teachers = JsonConvert.DeserializeObject<List<GDTeacher>>(gdTeachers);
			teachers.ForEach(t => t.GroupDisciplineId = gdId);

			var existedTeachers = JsonConvert.DeserializeObject<List<int>>(exitsedIds);

			_teacherService.SaveOrUpdateGDTeacher(teachers, existedTeachers);

			_unitOfWork.Commit();

			return Json(new { nextPage = Url.Action("Index") }, JsonRequestBehavior.AllowGet);
		}

		public ActionResult Delete(int id)
		{
			var groupdiscipline = _groupDisciplineService.GetAllGroupDisciplines().First(gd => gd.Id == id);
			var groupDisciplineViewModel = Mapper.Map<GroupDiscipline, GroupDisciplineViewModel>(groupdiscipline);
			return View(groupDisciplineViewModel);
		}

		[HttpPost, ActionName("Delete")]
		public ActionResult DeleteConfirmed(int id)
		{
			_groupDisciplineService.DeleteGroupDiscipline(id);
			_unitOfWork.Commit();
			return RedirectToAction("Index");
		}

		public JsonResult GetGroups()
		{
			var groups = _groupService.GetAllGroups().ToList();
			var groupViewModels = Mapper.Map<IEnumerable<Group>, IEnumerable<GroupViewModel>>(groups);

			return Json(new { groupViewModels }, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetDisciplines()
		{
			var disciplines = _academicDisciplineService.GetAll().ToList();
			var disciplineViewModels =
				Mapper.Map<IEnumerable<AcademicDiscipline>, IEnumerable<AcademicDisciplineViewModel>>(disciplines);

			return Json(new { disciplineViewModels }, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetTeachers()
		{
			var teachers = _teacherService.GetAllTeachers();
			var teacherViewModels = Mapper.Map<IEnumerable<Teacher>, IEnumerable<TeacherViewModel>>(teachers);

			return Json(new { teacherViewModels }, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public JsonResult SaveGroupDiscipline(int groupId, int disciplineId, string gdTeachers)
		{
			var groupDiscipline = new GroupDiscipline();
			groupDiscipline.GroupId = groupId;
			groupDiscipline.DisciplineId = disciplineId;

			var teachers = JsonConvert.DeserializeObject<List<GDTeacher>>(gdTeachers);
			teachers.ForEach(t => t.GroupDiscipline = groupDiscipline);

			_groupDisciplineService.SaveOrUpdate(groupDiscipline);

			foreach (var teacher in teachers)
			{
				_teacherService.SaveOrUpdateGDTeacher(teacher);
			}

			_unitOfWork.Commit();

			return Json(new { nextPage = Url.Action("Index") }, JsonRequestBehavior.AllowGet);
		}
	}
}

MSHRCS.Presentation/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MSHRCS.BusinessLogic;
using MSHRCS.BusinessLogic.DTO;
using MSHRCS.BusinessLogic.Services.Interfaces;
using MSHRCS.Presentation.Models;
using PagedList;

namespace MSHRCS.Presentation.Controllers
{
	public class TablesController : Controller
	{
		private readonly IGDCabinetService _gdCabinetService;

		public TablesController(IGDCabinetService gdCabinetService)
		{
			_gdCabinetService = gdCabinetService;
		}

		[HttpGet]
		public ActionResult GeneralTable()
		{
			var rowValues = _gdCabinetService.GetGeneralTableRowValues(DateTime.Now);
			var generalTableViewModel = GetGeneralTableViewModel(rowValues, 1);

			return View(generalTableViewModel);
		}

		[HttpGet]
		public ActionResult AdditionalTable()
		{
			return View();
		}

		[HttpGet]
		public PartialViewResult GetGeneralTableData(
			string group,
			int timeId,
			string teacher,
			string cabinet,
			string discipline,
			int? page)
		{
			var pageNumber = page ?? 1;
			var rowValues = _gdCabinetService.GetGeneralTableRowValues(DateTime.Now).Where(value => value.Group.StartsWith(group)).ToList();

			if (timeId != 0)
			{
				rowValues = rowValues.Where(value => value.TimeId == timeId).ToList();
			}

			if (!string.IsNullOrWhiteSpace(teacher))
			{
				rowValues = rowValues.Where(value => value.Teacher.Contains(teacher)).ToList();
			}

			if (!string.IsNullOrWhiteSpace(cabinet))
			{
				rowValues = rowValues.Where(value => value.Cabinet.StartsWith(cabinet)).ToList();
			}

			if (!string.IsNullOrWhiteSpace(discipline))
			{
				rowValues = rowValues.Where(value => value.AcademicDiscipline.StartsWith(discipline)).ToList();
			}

			var generalTableViewModel = GetGeneralTableViewModel(rowValues, pageNumber);
			generalTableViewModel.Group = group;
			generalTableViewModel.TimeId = timeId;
			generalTableViewModel.Teacher = teacher;
			generalTableViewModel.Cabinet = cabinet;
			generalTableViewModel.Discipline = discipline;

			return PartialView(generalTableViewModel);
		}

		private static GeneralTableViewModel GetGeneralTableViewModel(IEnumerable<GeneralTableRowValue> rowValues, int pageNumber)
		{
			var generalTableViewModel = new GeneralTableViewModel();
			generalTableViewModel.RowValues = rowValues.ToPagedList(pageNumber, Constants.PageSize);
			return generalTableViewModel;
		}
	}
}

MSHRCS.Presentation/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using MSHRCS.BusinessLogic;
using MSHRCS.BusinessLogic.Services.Interfaces;
using MSHRCS.Presentation.Helpers;
using MSHRCS.Presentation.Models;

namespace MSHRCS.Presentation.Controllers
{
	public class UserController : Controller
	{
		private readonly IUserService _userService;

		public UserController(IUserService userService)
		{
			_userService = userService;
		}

		[HttpGet]
		public ActionResult LogIn()
		{
			ViewBag.Users = _userService.GetAll();
			return View();
		}

		[HttpPost]
		public JsonResult LogIn(LogInUserViewModel logInUserViewModel)
		{
			if (!ModelState.IsValid)
			{
				return Json(new { success = false, message = Constants.ErrorMessage });
			}

			var password = AuthorizationHelper.GetHashString(logInUserViewModel.Password);
			var user = _userService.CheckUserExists(logInUserViewModel.UserId, password);

			if (user == null)
			{
				return Json(new { success = false, message = "Неправильный пароль!" });
			}

			FormsAuthentication.SetAuthCookie(user.Name, logInUserViewModel.RememberMe);
			GlobalStoreHelper.SetSession(user);

			return Json(new { success = true, nextPage = Url.Action("Index", "Home") }, JsonRequestBehavior.AllowGet);
		}

		public ActionResult LogOut()
		{
			FormsAuthentication.SignOut();
			Session[Constants.SessionKeyUser] = null;

			return RedirectToAction("Index", "Home");
		}
	}
}

MSHRCS.Presentation/Views/Shared/_Header.cshtml
<div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Расписание МГВРК", "Index", "Home")</li>
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Таблицы <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Главная таблица", "GeneralTable", "Tables")</li>
                                <li>@Html.ActionLink("Допонительная таблица", "AdditionalTable", "Tables")</li>
                            </ul>
                        </li>
                    }
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Редактирование <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Расписание", "Index", "GDCabinet")</li>
                                <li>@Html.ActionLink("Предметы", "Index", "AcademicDisciplines")</li>
                                <li><a href="#">Преподаватели</a></li>
                                <li><a href="#">Кабинеты</a></li>
                                <li><a href="#">Группы</a></li>
                                <li>@Html.ActionLink("Предметы в группах", "Index", "GroupDiscipline")</li>
                            </ul>
                        </li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li class="navbar-text">Добро пожаловать, @Context.User.Identity.Name!</li>
                        <li>@Html.ActionLink("Выйти", "LogOut", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Войти", "LogIn", "User")</li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</div>

MSHRCS.Presentation/Views/Shared/_JsUrls.cshtml
<script type="text/javascript">
    var logIn = '@Url.Action("LogIn", "User")';
    var generalTableData = '@Url.Action("GetGeneralTableData", "Tables")';
    var groupViewModels = '@Url.Action("GetGroups", "GroupDiscipline")';
    var disciplineViewModels = '@Url.Action("GetDisciplines", "GroupDiscipline")';
    var teachersViewModels = '@Url.Action("GetTeachers", "GroupDiscipline")';
    var saveGroupDiscipline = '@Url.Action("SaveGroupDiscipline", "GroupDiscipline")';
    var saveGroupDisciplineList = '@Url.Action("Edit", "GroupDiscipline")';
    var getGroupDisciplineViewModels = '@Url.Action("GetGroupDisciplineViewModels", "GDCabinet")';
    var getCabinetLessonViewModels = '@Url.Action("GetCabinetLessonViewModels", "GDCabinet")';
</script>

MSHRCS.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="@Url.Content("~/Scripts/jquery-2.1.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/moment.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datepicker.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/locales/bootstrap-datepicker.ru.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/typeaheads.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/typeahead.jquery.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/typeahead.bundle.min.js")" type="text/javascript"></script>

    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/typeahead.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-datepicker.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Custom.css")" rel="stylesheet" type="text/css" />
</head>

<body class="container col-md-8 col-md-offset-2">
    @Html.Partial("_Header")
    <div>
        @RenderBody()
    </div>
    @Html.Partial("_Footer")
</body>

@Html.Partial("_JsUrls")
</html>